# Generated by Django 4.1.5 on 2023-02-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile',
            field=models.ImageField(default='exit', upload_to='images/'),
            preserve_default=False,
        ),
    ]
