# Generated by Django 4.1.5 on 2023-01-30 05:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('MUV', 'MUV'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback')], default='Sedan', max_length=1000)),
                ('description', models.CharField(max_length=1500)),
                ('model_year', models.CharField(max_length=1000)),
                ('engine_type', models.CharField(choices=[('Electric', 'Electric'), ('Diesel', 'Diesel'), ('Petrol', 'Petrol')], default='Petrol', max_length=1000)),
                ('gear_type', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual')], default='Manual', max_length=1000)),
                ('total_km', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cars',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('discount_percentage', models.FloatField(validators=[django.core.validators.MaxValueValidator(99.99)])),
                ('is_active', models.BooleanField(default=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=1000)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.TextField()),
                ('drop_location', models.TextField()),
                ('pickup_date', models.DateField()),
                ('drop_date', models.DateField()),
                ('pickup_hour', models.TimeField(default='09:00:00')),
                ('drop_hour', models.TimeField(default='21:00:00')),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled')], default='Booked', max_length=1000)),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_type', models.CharField(default='Card', max_length=1000)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
                ('discount_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.discount')),
                ('services', models.ManyToManyField(to='cars.services')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookings',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
