# Generated by Django 4.1.5 on 2023-02-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_bookings_modified_at_alter_cars_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='services',
            field=models.ManyToManyField(null=True, to='cars.services'),
        ),
    ]
